name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release version
        default: "0.1"
        required: true
      next-version:
        description: Next version
        default: "0.2"
        required: true

jobs:
  release-ui:
    name: Release UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "carlosthe19916/controls-ui"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Git setup
        run: |
          git config user.name "Carlos Feria"
          git config user.email "<carlosthe19916@gmail.com>"
      - name: Create tag
        run: |
          ls
          git tag ${{ github.event.inputs.release-version }}
          git push "https://${{ env.GH_PAT }}@github.com/carlosthe19916/controls-ui.git" --tags
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GH release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ github.event.inputs.release-version }}
          release_name: Release ${{ github.event.inputs.release-version }}
          draft: false
          prerelease: false
          owner: carlosthe19916
          repo: controls-ui
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Build
        run: |
          yarn install
          yarn build
      - name: Push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@3.02
        with:
          registry: quay.io
          name: carlosthe19916/controls-ui
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
          dockerfile: Dockerfile
          snapshot: false
          tags: "${{ github.event.inputs.release-version }}"
