name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release version
        default: "0.1"
        required: true
      next-version:
        description: Next version
        default: "0.2-SNAPSHOT"
        required: true

jobs:
  controls:
    name: Controls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "carlosthe19916/poc"
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Git tag
        run: |
          cd controls

          mvn versions:set -DnewVersion="${{ github.event.inputs.release-version }}"
          git add .
          git commit -m "Release ${{ github.event.inputs.release-version }}"

          git tag ${{ github.event.inputs.release-version }}
      - name: Build
        run: |
          cd controls

          mvn package -Pnative \
          -Dquarkus.native.container-build=true \
          -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.3.0.0.Final-java11
      - name: Push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: quay.io
          name: carlosthe19916/controls
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
          dockerfile: src/main/docker/Dockerfile.native
          snapshot: false
          tags: "${{ github.event.inputs.release-version }}"
          workdir: controls
      - name: Prepare next version
        run: |
          cd controls

          mvn versions:set -DnewVersion="${{ github.event.inputs.next-version }}"
          git add .
          git commit -m "Prepare next release ${{ github.event.inputs.next-version }}"
      - name: Github push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main
          tags: true
          repository: carlosthe19916/poc
      - name: Github release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: refs/tags/${{ github.event.inputs.release-version }}
          release_name: Release refs/tags/${{ github.event.inputs.release-version }}
          draft: false
          prerelease: false
          owner: carlosthe19916
          repo: poc
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  ui:
    name: UI
    runs-on: ubuntu-latest
    needs: [controls]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "carlosthe19916/controls-ui"
          persist-credentials: false
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Git tag
        run: |
          git tag ${{ github.event.inputs.release-version }}
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: quay.io
          name: carlosthe19916/controls-ui
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
          dockerfile: Dockerfile
          snapshot: false
          tags: "${{ github.event.inputs.release-version }}"
      - name: Github push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: master
          tags: true
          repository: carlosthe19916/controls-ui
      - name: Github release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: refs/tags/${{ github.event.inputs.release-version }}
          release_name: Release refs/tags/${{ github.event.inputs.release-version }}
          draft: false
          prerelease: false
          owner: carlosthe19916
          repo: controls-ui
          commitish: master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  keycloak-theme:
    name: Keycloak theme
    runs-on: ubuntu-latest
    needs: [ui]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "carlosthe19916/controls-keycloak-theme"
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Git tag
        run: |
          mvn versions:set -DnewVersion="${{ github.event.inputs.release-version }}"
          git add .
          git commit -m "Release ${{ github.event.inputs.release-version }}"

          git tag ${{ github.event.inputs.release-version }}
      - name: Build
        run: mvn -e -B -DskipTests=true -DskipDocs clean install
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
      - name: Prepare next version
        run: |
          mvn versions:set -DnewVersion="${{ github.event.inputs.next-version }}"
          git add .
          git commit -m "Prepare next release ${{ github.event.inputs.next-version }}"
      - name: Github push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: master
          tags: true
          repository: carlosthe19916/controls-keycloak-theme
      - name: Github release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: refs/tags/${{ github.event.inputs.release-version }}
          release_name: Release refs/tags/${{ github.event.inputs.release-version }}
          draft: false
          prerelease: false
          owner: carlosthe19916
          repo: controls-keycloak-theme
          commitish: master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
